spring:
  profiles:
    active: test
  shardingsphere:
    enabled: false # 关闭自动注解使用Java Config 的方式


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  config: classpath:log4j2.xml



